#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_JAKE,
    SP_NAME_REEVE,
    SP_NAME_PREM,
    SP_NAME_JAISON,
    SP_NAME_PRAJITH,
    SP_NAME_VARUN,
    SP_NAME_SNEHAL,
    SP_NAME_RAJESH,
    SP_NAME_PAWAN,
    SP_NAME_PRAJESH,
    SP_NAME_HANSTON,
    SP_NAME_PREMAL,
    SP_NAME_RASHEL,
    SP_NAME_DON,
    SP_NAME_AKSHARA,
    SP_NAME_DARA,
    SP_NAME_GILSTON,
    SP_NAME_DELSON,
    SP_NAME_MONVISH,
    SP_NAME_DARWIN,
    SP_NAME_ADITHYA,
    SP_NAME_HANDAM,
    SP_NAME_RION,
    SP_NAME_DEON,
    SP_NAME_MANVITHA,
    SP_NAME_KEVIN,
    SP_NAME_LOHITH,
    SP_NAME_ANMOL,
    SP_NAME_ARSHAD,
    SP_NAME_MELWIN,
    SP_NAME_YASHAS,
    SP_NAME_BENNY,
    SP_NAME_ANNOUNCER,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
