// DO NOT MODIFY THIS FILE! It is auto-generated by tools/learnset_helpers/make_teachables.py
// Set the config P_TUTOR_MOVES_ARRAY in include/config/pokemon.h to TRUE to enable this array!

const u16 gTutorMoves[] = {
    MOVE_COUNTER,
    MOVE_DEFENSE_CURL,
    MOVE_DREAM_EATER,
    MOVE_DYNAMIC_PUNCH,
    MOVE_ENDURE,
    MOVE_EXPLOSION,
    MOVE_FURY_CUTTER,
    MOVE_MEGA_KICK,
    MOVE_MEGA_PUNCH,
    MOVE_MIMIC,
    MOVE_ROLLOUT,
    MOVE_SEISMIC_TOSS,
    MOVE_SNORE,
    MOVE_SOFT_BOILED,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE
};
